# Generated by Django 5.2.1 on 2025-06-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['tutorial_title__title_id_slug', 'question_id_slug'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
