from django.shortcuts import render
from django_spellbook.views import render_spellbook_markdown

# Views will be auto-generated by Spellbook for markdown content
# Custom views can be added here if needed
